apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-crawler
  labels:
    app: synergychat-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-crawler  # should match metadata/labels/app
  template:
    metadata:
      labels:
        app: synergychat-crawler  # should match metadata/labels/app
    spec:
      containers:
        - name: synergychat-crawler
          image: bootdotdev/synergychat-crawler:latest
          envFrom:
            - configMapRef:
                name: synergychat-crawler-configmap
